version: "3.8"

services:
  grpc_db:
    image: mongo:latest
    container_name: grpc_db
    expose:
      - "27017"
    volumes:
      - /usr/local/var/mongodb:/data/db
    restart: "unless-stopped"

  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"

  grpc_server:
    container_name: grpc_server
    expose:
      - "9000"
    ports:
      - "50051:50051"
    build:
      context: ./
    restart: "unless-stopped"
